server:
  port: 8443

spring:
  cache:
    type: ehcache
    cache-names: inventory
    ehcache:
      config: classpath:ehcache.xml
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: 
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate.dialect: org.hibernate.dialect.H2Dialect
      
             
